### ISSUE TITLE
website_product_manufacturer

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/e-commerce#1]
Menampilkan informasi mengenai manufacturer produk pada tiap halaman produk

Dependensi:
- website_sale
- product_manufacturer

Acceptance Criteria:
1. Muncul atau tidaknya manufacturer dikontrol oleh toggle pada menu customize
2. Jika field manufacturer tidak diisi, maka info manufacturer == "N/A"

**Comment by andhit-r** [comment]
@azmimr67 tolong dibantu penempatan posisi informasi manufacturernya yah

**Comment by azmimr67** [comment]
Kalau menurut saya dibawah nama produk

**Comment by andhit-r** [comment]
@mikevhe18 ini juga sudah bisa mulai dikerjalan yah
